const nameGirl = 'Thanh Chúc:33';
const giftUrl = 'https://zalo.me/0362227656';
const eventName = 'Chúc Mừng năm mới';
const titleCard = 'Tặng ebe Thanh Chúc của tuii';
const contentCard = 'Hôm nay là ngày đầu tiên của năm mới, Chúc yêu dấu! 💐Nhân ngày đặc biệt này, anh chỉ muốn nói rằng anh rất biết ơn vì có em trong cuộc đời, Em là người con gái tuyệt vời nhất mà anh từng gặp, Anh biết rằng trong thời gian đầu của chúng mình cũng tại ah mà đã xảy ra nhiều chuyện hiểu lầm những chuyện không hề mong muốn, Nhưng ah rất vui vì e đã tin ah và tha thứ cho anh để anh có thể chứng minh tình yêu của mình dành cho em, Không biết tới hiện tại em tin anh được bao nhiêu hay tình cảm của e dành cho anh nhiều tới mức nào, Nhưng điều ah hi vọng nhất là ah muốn được cùng e mãi mãi đi trên cùng một con đường, Và ah hi vọng rằng trong năm này và cả những năm về sau sẽ có e luôn bên cạnh ah, Điều anh mong muốn nhất là được nhìn thấy em luôn vui vẻ và cười tươi, Anh không chắc rằng anh có thể làm tất cả mọi thứ vì em, ah cũng ko có gì tài giỏi cả nhưng e nên nhớ anh vẫn luôn hướng tới e, ưu tiên e và làm tất cả những thứ ah có thể làm để e được cảm thấy hạnh phúc - vui vẻ khi e yêu ah, Đó là điều anh mong muốn nhất và điều cuối cùng ah muốn nói với e là dù có chuyện gì thì chúng mình cùng nhau vượt qua đừng nói những lời không hay và cũng đừng giấu nhau bất kì chuyện vui hay buồn nếu cần cứ việc chia sẻ nói với ah và ah vẫn sẽ luôn lắng nghe với an ủi em.Năm mới này ah cũng chúc em luôn vui vẻ, học giỏi hơn, xinh đẹp hơn, tất cả may mắn sẽ tới với em và em sẽ luôn iu anh nhìu hơn. Thật sự anh yêu em rất nhiều! ❤️'
// phần dưới dành cho các bạn biết code, nếu muốn chỉnh ảnh đơn giản với base64
// Cần hỗ trợ hãy liên hệ: 
// Mr-Nam http://facebook.com/nam.nodemy
// Các bạn muốn học lập trình thì tham gia Nhóm zalo tự học lập trình nhé: https://zalo.me/g/yhdkef092
const giftImage = 'tho.png';
const base64 = '';
const giftImageBase64 = "data:image/png;base64, " + base64;
